# PostgreSQL
spring.jpa.hibernate.ddl-auto=create

spring.datasource.url=postgres://ogeezhyeznilnh:83879e26eb243f91db6cfbd98cf022864b6ef9820afaf3605b9eb706996fe13b@ec2-54-144-165-97.compute-1.amazonaws.com:5432/db3vmu8pu5ibl9

# Exibe os camandos SQL
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.type=info

