# MySQL
spring.jpa.hibernate.ddl-auto=create

spring.datasource.url=mysql://b1d1c0f27e6630:47af1227@us-cdbr-east-04.cleardb.com/heroku_4cdbb00001c59ad?reconnect=true

# Exibe os camandos SQL
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.type=info

